// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { URL } from "url";
loadEnv({ path: ".env.local" });
loadEnv({ path: ".env" });
import { defineConfig } from "prisma/config";

function normalizeConnectionString(raw?: string): string | undefined {
  if (!raw) return undefined;
  try {
    const url = new URL(raw);
    const params = url.searchParams;
    if (process.env.DB_SSL_NO_VERIFY === "true") {
      params.set("sslmode", "no-verify");
    } else if (process.env.PGSSLMODE) {
      params.set("sslmode", process.env.PGSSLMODE);
    }
    if (params.get("sslmode") === "require" && !params.has("uselibpqcompat")) {
      params.set("uselibpqcompat", "true");
    }
    url.search = params.toString();
    return url.toString();
  } catch {
    return raw;
  }
}

const databaseUrl = normalizeConnectionString(
  process.env["DATABASE_URL"] ||
    process.env["POSTGRES_PRISMA_URL"] ||
    process.env["POSTGRES_URL"] ||
    process.env["POSTGRES_URL_NON_POOLING"] ||
    (process.env["POSTGRES_DATABASE"] && process.env["POSTGRES_HOST"] && process.env["POSTGRES_USER"] && process.env["POSTGRES_PASSWORD"]
      ? `postgres://${process.env["POSTGRES_USER"]}:${process.env["POSTGRES_PASSWORD"]}@${process.env["POSTGRES_HOST"]}/${process.env["POSTGRES_DATABASE"]}`
      : undefined)
);

if (!databaseUrl) {
  throw new Error("DATABASE_URL or an equivalent Supabase Postgres connection variable must be set.");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
